# Generated by Django 4.1.7 on 2023-04-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_practice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
